### ISSUE TITLE
NROW(estfun(object2)) for icci

### ISSUE THREAD

**Issue by maugavilla** [qpsy/nonnest2#6]
Hi Ed

Any reason to use NROW(estfun(object2)) in the icci function, instead of NROW(llA) or n ? 

I ask because If i want to use the function with other packages (like mclust) I can easily add the llcont function, but the function still fails because they dont have an "estfun" method. While the estfun is not used anywhere else

thanks

**Comment by ecmerkle** [comment]
I imagine that was copy and pasted from `vuongtest()`. I will look at it soon. In the meantime, sometimes it can help to do `library(sandwich)` because it defines a generic estfun method.

**Comment by maugavilla** [comment]
Sounds good, I mentioned it because the esftfun is not used anywhere else in the function. 

It seems the generic method doesnt work for mclust models

I will be testing this as a method to compare latent class analysis models

thanks

**Comment by ecmerkle** [comment]
I will send it to CRAN soon unless some other change is needed.

**Comment by maugavilla** [comment]
great thanks. I cant think of another change for now
